<h1>Current Status</h1>
<aside>
    <span class="hdr">Aside</span>
    <p>Aside is optional. Use class='mainContent full' on container div to make content fill area</p>
    <span class="hdr">Crazy filler content</span>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse dapibus pharetra neque, ut volutpat massa sagittis quis. Sed venenatis tempor orci in ullamcorper. Fusce posuere eros id lacus porttitor imperdiet. Vestibulum sed mauris massa, quis varius nisi. Nullam accumsan lacinia tortor, vel sagittis diam posuere id. In hac habitasse platea dictumst. In hac habitasse platea dictumst. Mauris porta ante vitae est scelerisque porttitor. Pellentesque tristique nisl id nisi aliquet et tincidunt urna congue. In elit est, auctor ac ornare ut, viverra ut dolor. Duis sed urna vitae odio sagittis posuere. Sed accumsan erat in urna consequat in ornare sapien tincidunt.
    </p>
</aside>
<div class="mainContent">
    <div class="msg">Success! This is a green status message</div><br />
    <div class="msg error">Error! This is an error messasge</div><br />
    <p>These will be 100% "header" messages displayed above h1 that are part of the template, these are here for demonstration purposes of the css classes.</p>
    <h2>Begin crazy content</h2>
    <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse dapibus pharetra neque, ut volutpat massa sagittis quis. Sed venenatis tempor orci in ullamcorper. Fusce posuere eros id lacus porttitor imperdiet. Vestibulum sed mauris massa, quis varius nisi. Nullam accumsan lacinia tortor, vel sagittis diam posuere id. In hac habitasse platea dictumst. In hac habitasse platea dictumst. Mauris porta ante vitae est scelerisque porttitor. Pellentesque tristique nisl id nisi aliquet et tincidunt urna congue. In elit est, auctor ac ornare ut, viverra ut dolor. Duis sed urna vitae odio sagittis posuere. Sed accumsan erat in urna consequat in ornare sapien tincidunt.
    </p>
    <p>
    Nunc blandit lorem ac urna posuere congue. Nam posuere lectus magna, quis sollicitudin neque. Ut a tortor sed turpis tincidunt volutpat. Nulla sit amet enim massa, ultricies porta magna. Morbi lectus purus, adipiscing id lobortis in, scelerisque id orci. Cras mauris odio, rhoncus non suscipit sit amet, ullamcorper vel neque. Nulla erat urna, pulvinar eu rutrum in, sodales vitae turpis. Integer rhoncus malesuada varius.
    </p>
    <p>
    Nam nibh neque, dictum sit amet egestas sed, condimentum eu urna. Curabitur condimentum magna eget sem accumsan imperdiet. Mauris in lacinia erat. Aenean at rutrum libero. Pellentesque nibh nulla, pharetra eu volutpat non, tincidunt id metus. Cras scelerisque interdum tellus, vitae gravida orci molestie id. Pellentesque sollicitudin mi eget quam gravida commodo. Praesent consectetur molestie nisl quis mollis. Nullam faucibus volutpat ipsum id interdum.
    </p>

</div>